Add TSC members as maintainers
opensearch-project/technical-steering pull request #8
Opened 2024-10-27 14:51 UTC by krisfreedain

### Description
Add TSC members as MAINTAINERS - as discussed & approved in Oct 16 meeting

### Issues Resolved
N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-27 14:58 UTC, dblock requested changes
I've added the folks in CODEOWNERS as Maintainers. Once everyone accepted their pending invites we can merge this.

2024-10-27 15:00 UTC, dblock commented
![Screenshot 2024-10-27 at 10 59 50 AM](https://github.com/user-attachments/assets/b871c32e-71c4-4b84-b879-aaeb1745e032)

2024-10-27 15:01 UTC, dblock commented on MAINTAINERS.md
> +| Kris Freedain             | [krisfreedain](https://github.com/krisfreedain)     | Amazon      |
@krisfreedain Sort this alphabetically?

2024-10-28 16:34 UTC, reta approved these changes

2024-10-31 17:15 UTC, krisfreedain commented on MAINTAINERS.md
> +| Kris Freedain             | [krisfreedain](https://github.com/krisfreedain)     | Amazon      |
done

2024-10-31 17:16 UTC, dblock approved these changes

2024-10-31 17:16 UTC, merged